# Generated by Django 3.1.7 on 2021-02-24 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(help_text='Enter a book genre(eg science fiction)', max_length=200),
        ),
    ]
